### ISSUE TITLE
pemstore.Download and pemstore.Store signature seems inconsistent

### ISSUE THREAD

**Issue by Warashi** [takayukioda/pemstore#3]
https://github.com/takayukioda/pemstore/blob/a64cabcbdc5e0061ca8efc196490e80baa278e62/pemstore.go#L8-L10
`pemstore.Download` returns `string`, but `pemstore.Store` requires `[]data`. It seems inconsistent.

**Comment by takayukioda** [comment]
Hmm, I see.
~I started to build with CLI tool which "Download" is not about get bytes but get file. But I guess it's interface for command line tool but not library itself.~
No, it was returned with string because its internal implementation returns string. It wasn't about CLI 🤦🏽 

I'll update the interface 👍🏽
